openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /items:
    get:
      summary: Get items
      description: Returns a list of items.
      parameters:
        - name: id
          in: path
          required: true
          description: The item ID.
          schema:
            type: string
        - name: filter
          in: query
          required: false
          description: Filter for items.
          schema:
            type: string
      responses:
        '200':
          description: A list of items.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
