openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /items:
    get:
      summary: Get items
      description: Returns a list of items.
      parameters:
        - name: id
          in: path
          required: true
          description: The item ID.
          schema:
            type: string
        - name: filter
          in: query
          required: false
          description: Filter for items.
          schema:
            type: string
      responses:
        '200':
          description: A list of items.
          content:
            application/json:
              schema:
                title: 'ItemResponse'
                type: object
                properties:
                  items:
                    title: 'Items'
                    type: array
                    items:
                      title: 'Item'
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          title: Description
                          type: object
                          properties:
                            id:
                              type: string
                        history:
                          type: array
                          items:
                            type: object
                            properties:
                              age:
                                type: string
